# Abstract base class
# to predict in Automl class without training with the default_model,
# which was trained on all 20 datasets;
# when mlr3-learner is generated by learner = make_mlr3_learner(AutomlCustom):
# learner$automl$model$automl$model$predict(task)
# else: error will be returned to remind, that it should be trained
source('code/module_functions.R')
load("./results/default_model.RData")

library(R6)
Automl = R6Class(
  "Automl",
  public = list(
    
    model = default_model,
    
    train = function(data) {
      stop("Not implemented.")
      invisible(self) # important!
    },
    
    predict = function(newdata) {
      stop("Not implemented.")
    }
  )
)

AutomlCustom = R6Class(
  "AutomlCustom",
  inherit = Automl,
  public = list(
    train = function(data) {
      self$model = train_helper(data)
# implementation here!
      invisible(self) # important!
    },
    
    predict = function(newdata) {
      #implementation here!
      ndata = newdata
      self$model$predict_newdata(ndata)$response # change newdata by data
    }
    
  )
  
)

